apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-fastapi
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.fastapi.image_name }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@wiki-postgres:5432/{{ .Values.postgresql.auth.database }}"
        resources:
          {{- toYaml .Values.fastapi.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-fastapi
spec:
  selector:
    app: fastapi
  ports:
  - port: 8000
    targetPort: 8000
