apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://wiki-prometheus:9090
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
data:
  creation.json: |
    {
      "annotations": {"list": []},
      "editable": true,
      "id": 678,
      "panels": [{
        "datasource": {"type": "prometheus"},
        "fieldConfig": {
          "defaults": {
            "color": {"mode": "palette-classic"},
            "custom": {"drawStyle": "line", "fillOpacity": 10, "lineWidth": 1},
            "unit": "reqps"
          }
        },
        "gridPos": {"h": 9, "w": 24, "x": 0, "y": 0},
        "id": 1,
        "targets": [
          {"expr": "rate(users_created_total[5m])", "refId": "A", "legendFormat": "User Creation Rate"},
          {"expr": "rate(posts_created_total[5m])", "refId": "B", "legendFormat": "Post Creation Rate"}
        ],
        "title": "User and Post Creation Rates",
        "type": "timeseries"
      }],
      "title": "Creation Dashboard",
      "uid": "creation-dashboard-678",
      "version": 1
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.2
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.grafana.adminUser }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.adminPassword }}
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboards-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboard
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: dashboards-provider
        configMap:
          name: grafana-dashboards-provider
      - name: dashboard
        configMap:
          name: grafana-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
